import type { WorkPlanSection, WorkflowDefinition, WorkflowTemplate } from "../types/workMode";

export const workflows: WorkflowDefinition[] = [
  {
    id: "slide_deck",
    label: "Investor / Slide Deck Roadmap",
    description: "Creates an editable roadmap for presentations, investor decks, and competitor narratives.",
    skillId: "investor_deck_builder",
    taskCategory: "presentation",
    intentCategory: "drafting",
    supportedRoles: ["Founder", "Researcher", "Product Manager", "Executive"],
    supportedArtifacts: ["PPT", "Strategy Memo", "Competitive Analysis", "Research Report"],
    keywordSignals: ["ppt", "presentation", "slides", "deck", "pitch", "investor", "competitor", "market"],
    defaultModuleIds: ["assumptions", "validation_checklist"],
    optionalModuleIds: ["competitor_analysis", "market_landscape", "investor_framing", "sources_required", "metrics"],
    defaultDepth: "L3",
  },
  {
    id: "prd_generation",
    label: "Product Requirements Roadmap",
    description: "Creates an editable roadmap for PRDs, feature specs, BRDs, and product planning.",
    skillId: "prd_builder",
    taskCategory: "product",
    intentCategory: "planning",
    supportedRoles: ["Product Manager", "Founder", "Business Analyst", "Designer"],
    supportedArtifacts: ["PRD", "BRD", "Technical Design", "Strategy Memo"],
    keywordSignals: ["prd", "feature", "requirement", "requirements", "user story", "roadmap", "mvp", "metrics"],
    defaultModuleIds: ["assumptions", "user_personas", "metrics", "risk_analysis", "validation_checklist"],
    optionalModuleIds: ["competitor_analysis", "implementation_plan", "sources_required"],
    defaultDepth: "L2",
  },
  {
    id: "debugging_bug_fix",
    label: "Debugging / Bug Fix Roadmap",
    description: "Creates an editable roadmap for debugging, fixes, implementation review, and verification.",
    skillId: "bug_fix_planner",
    taskCategory: "engineering",
    intentCategory: "debugging",
    supportedRoles: ["Developer"],
    supportedArtifacts: ["Code", "Technical Design"],
    keywordSignals: ["bug", "error", "fix", "debug", "crash", "test", "api", "database", "regression"],
    defaultModuleIds: ["assumptions", "root_cause_analysis", "test_cases", "validation_checklist", "risk_analysis"],
    optionalModuleIds: ["api_examples", "database_schema", "implementation_plan", "sources_required"],
    defaultDepth: "L2",
  },
  {
    id: "backend_software",
    label: "Backend Software Roadmap",
    description: "Creates an editable roadmap for APIs, services, data models, auth, queues, and backend delivery.",
    skillId: "backend_api_builder",
    taskCategory: "backend",
    intentCategory: "implementation",
    supportedRoles: ["Developer", "Software Architect"],
    supportedArtifacts: ["Backend API", "Code", "Technical Design", "Implementation Plan"],
    keywordSignals: ["backend", "api", "endpoint", "server", "service", "microservice", "database", "auth", "queue", "cache"],
    defaultModuleIds: ["assumptions", "implementation_plan", "api_examples", "database_schema", "test_cases", "validation_checklist"],
    optionalModuleIds: ["risk_analysis", "metrics", "tradeoff_analysis", "sources_required"],
    defaultDepth: "L3",
  },
  {
    id: "frontend_web",
    label: "Frontend Web Roadmap",
    description: "Creates an editable roadmap for web UI, components, state, accessibility, responsive behavior, and frontend testing.",
    skillId: "frontend_app_builder",
    taskCategory: "frontend",
    intentCategory: "implementation",
    supportedRoles: ["Developer", "Designer", "Product Manager"],
    supportedArtifacts: ["Frontend App", "Code", "Technical Design", "Implementation Plan"],
    keywordSignals: ["frontend", "web app", "react", "vue", "ui", "component", "responsive", "css", "browser", "accessibility"],
    defaultModuleIds: ["assumptions", "implementation_plan", "validation_checklist", "test_cases", "risk_analysis"],
    optionalModuleIds: ["user_personas", "metrics", "api_examples", "tradeoff_analysis", "sources_required"],
    defaultDepth: "L3",
  },
  {
    id: "architecture_review",
    label: "Architecture Review Roadmap",
    description: "Creates an editable roadmap for reviewing system design, scalability, reliability, security, and tradeoffs.",
    skillId: "architecture_reviewer",
    taskCategory: "technical_design",
    intentCategory: "review",
    supportedRoles: ["Software Architect", "Developer", "Executive"],
    supportedArtifacts: ["Architecture Review", "Technical Design", "Strategy Memo"],
    keywordSignals: ["architecture review", "review architecture", "system design", "scalability", "reliability", "distributed", "tradeoff"],
    defaultModuleIds: ["assumptions", "risk_analysis", "validation_checklist", "implementation_plan"],
    optionalModuleIds: ["api_examples", "database_schema", "metrics", "tradeoff_analysis", "sources_required"],
    defaultDepth: "L4",
  },
  {
    id: "research_report",
    label: "Research Report Roadmap",
    description: "Creates an editable roadmap for source-aware research, synthesis, comparisons, and recommendations.",
    skillId: "research_synthesizer",
    taskCategory: "research",
    intentCategory: "research",
    supportedRoles: ["Researcher", "Founder", "Executive", "Business Analyst"],
    supportedArtifacts: ["Research Report", "Competitive Analysis", "Strategy Memo"],
    keywordSignals: ["research", "report", "sources", "citations", "literature", "market research", "evidence", "synthesize"],
    defaultModuleIds: ["assumptions", "sources_required", "validation_checklist"],
    optionalModuleIds: ["competitor_analysis", "market_landscape", "risk_analysis", "metrics"],
    defaultDepth: "L3",
  },
  {
    id: "analytics_plan",
    label: "Analytics Roadmap",
    description: "Creates an editable roadmap for datasets, SQL, metrics, dashboards, experiments, and insight validation.",
    skillId: "analytics_planner",
    taskCategory: "data",
    intentCategory: "analysis",
    supportedRoles: ["Data Analyst", "Business Analyst", "Product Manager", "Executive"],
    supportedArtifacts: ["Data Analysis", "Strategy Memo", "Research Report"],
    keywordSignals: ["analytics", "data analysis", "dataset", "sql", "dashboard", "cohort", "funnel", "experiment", "chart"],
    defaultModuleIds: ["assumptions", "metrics", "validation_checklist", "sources_required"],
    optionalModuleIds: ["risk_analysis", "implementation_plan", "market_landscape", "tradeoff_analysis"],
    defaultDepth: "L3",
  },
  {
    id: "complex_coding",
    label: "Complex Coding Roadmap",
    description: "Creates an editable roadmap for multi-file implementation, algorithms, integrations, tests, and rollout.",
    skillId: "complex_code_planner",
    taskCategory: "engineering",
    intentCategory: "implementation",
    supportedRoles: ["Developer", "Software Architect"],
    supportedArtifacts: ["Code", "Implementation Plan", "Technical Design"],
    keywordSignals: ["complex coding", "implement", "multi-file", "algorithm", "refactor", "integration", "library", "sdk", "build"],
    defaultModuleIds: ["assumptions", "implementation_plan", "test_cases", "validation_checklist", "risk_analysis"],
    optionalModuleIds: ["api_examples", "database_schema", "metrics", "tradeoff_analysis", "sources_required"],
    defaultDepth: "L3",
  },
  {
    id: "career_path",
    label: "Career Path Roadmap",
    description: "Creates an editable roadmap for career goals, skill gaps, learning plans, portfolio, resume, and interview prep.",
    skillId: "career_path_coach",
    taskCategory: "career",
    intentCategory: "coaching",
    supportedRoles: ["Career Coach", "Developer", "Designer", "Data Analyst", "Product Manager"],
    supportedArtifacts: ["Career Roadmap", "Strategy Memo"],
    keywordSignals: ["career", "career path", "learning path", "roadmap to become", "resume", "cv", "interview", "portfolio", "job search"],
    defaultModuleIds: ["assumptions", "implementation_plan", "metrics", "validation_checklist"],
    optionalModuleIds: ["risk_analysis", "sources_required"],
    defaultDepth: "L2",
  },
  {
    id: "generic_workflow",
    label: "Generic Work Roadmap",
    description: "Creates a neutral editable roadmap when the prompt does not clearly fit a specialized workflow.",
    skillId: "general_workflow_planner",
    taskCategory: "general",
    intentCategory: "planning",
    supportedRoles: [
      "Product Manager",
      "Researcher",
      "Developer",
      "Software Architect",
      "Data Analyst",
      "Founder",
      "Business Analyst",
      "Designer",
      "Marketer",
      "Executive",
      "Career Coach",
      "Unknown",
    ],
    supportedArtifacts: [
      "General Roadmap",
      "Strategy Memo",
      "Research Report",
      "Technical Design",
      "Implementation Plan",
      "Unknown",
    ],
    keywordSignals: ["plan", "roadmap", "outline", "structure", "framework", "guide"],
    defaultModuleIds: ["assumptions", "validation_checklist", "implementation_plan"],
    optionalModuleIds: ["risk_analysis", "sources_required", "metrics", "tradeoff_analysis"],
    defaultDepth: "L2",
  },
];

function section(input: Omit<WorkPlanSection, "sourceRefs"> & { sourceRefs?: string[] }): WorkPlanSection {
  return {
    sourceRefs: [],
    ...input,
  };
}

export const workflowTemplates: WorkflowTemplate[] = [
  {
    id: "slide_deck",
    name: "Investor / Slide Deck Roadmap",
    artifacts: ["PPT", "Strategy Memo", "Competitive Analysis", "Research Report"],
    roles: ["Founder", "Researcher", "Product Manager", "Executive"],
    taskCategories: ["presentation", "analysis", "research"],
    keywordSignals: ["ppt", "presentation", "slides", "deck", "pitch", "investor", "competitor", "market"],
    defaultModules: ["assumptions", "validation_checklist"],
    optionalModules: ["competitor_analysis", "market_landscape", "investor_framing", "sources_required", "metrics", "risk_analysis"],
    defaultSourceMode: "source_needed_only",
    defaultDepth: "L3",
    sections: [
      section({
        id: "deck_goal",
        title: "Deck Goal",
        instructions: "Define the investor-facing purpose of the deck and the decision it should support.",
        required: true,
      }),
      section({
        id: "audience_and_context",
        title: "Audience And Context",
        instructions: "Clarify audience, stage, business context, and what the reader already knows.",
        required: true,
      }),
      section({
        id: "core_thesis",
        title: "Core Thesis",
        instructions: "State the central narrative the deck should prove or explore.",
        required: true,
      }),
      section({
        id: "market_landscape",
        title: "Market Landscape",
        instructions: "Map the category, market forces, segments, and relevant trends.",
        required: false,
        moduleId: "market_landscape",
      }),
      section({
        id: "competitor_set",
        title: "Competitor Set",
        instructions: "Identify the competitor or alternative set and why each belongs in scope.",
        required: true,
        moduleId: "competitor_analysis",
      }),
      section({
        id: "competitor_comparison",
        title: "Competitor Comparison",
        instructions: "Compare competitors across dimensions such as audience, distribution, pricing, product surface, and moat.",
        required: true,
        moduleId: "competitor_analysis",
      }),
      section({
        id: "positioning_matrix",
        title: "Positioning Matrix",
        instructions: "Define the axes and explain what position the subject should occupy.",
        required: false,
        moduleId: "competitor_analysis",
      }),
      section({
        id: "investor_narrative",
        title: "Investor Narrative",
        instructions: "Translate findings into the investor story: market timing, differentiation, moat, and upside.",
        required: false,
        moduleId: "investor_framing",
      }),
      section({
        id: "risks_and_open_questions",
        title: "Risks And Open Questions",
        instructions: "List risks, unresolved assumptions, and questions that affect credibility.",
        required: true,
        moduleId: "risk_analysis",
      }),
      section({
        id: "source_requirements",
        title: "Source Requirements",
        instructions: "Mark claims that need citations, user uploads, or external validation before final use.",
        required: true,
        moduleId: "sources_required",
      }),
      section({
        id: "validation_checklist",
        title: "Validation Checklist",
        instructions: "Define the checks the final answer must pass before generation.",
        required: true,
        moduleId: "validation_checklist",
      }),
    ],
    validationCriteria: [
      "Final output must be structured as a slide-by-slide deck outline.",
      "Investor-facing claims must be marked for source validation when sourceMode is not none.",
      "Competitor comparisons must include dimensions, not just descriptions.",
      "Missing context must be called out before answer generation.",
    ],
  },
  {
    id: "prd_generation",
    name: "Product Requirements Roadmap",
    artifacts: ["PRD", "BRD", "Technical Design", "Strategy Memo"],
    roles: ["Product Manager", "Founder", "Business Analyst", "Designer"],
    taskCategories: ["product", "business", "technical_design"],
    keywordSignals: ["prd", "feature", "requirement", "requirements", "user story", "roadmap", "mvp", "metrics"],
    defaultModules: ["assumptions", "user_personas", "metrics", "risk_analysis", "validation_checklist"],
    optionalModules: ["competitor_analysis", "implementation_plan", "sources_required", "api_examples", "database_schema"],
    defaultSourceMode: "none",
    defaultDepth: "L2",
    sections: [
      section({
        id: "product_context",
        title: "Product Context",
        instructions: "Summarize product area, current state, and why this work matters now.",
        required: true,
      }),
      section({
        id: "problem_statement",
        title: "Problem Statement",
        instructions: "Describe the user or business problem in testable terms.",
        required: true,
      }),
      section({
        id: "users_and_personas",
        title: "Users And Personas",
        instructions: "Define target users, personas, jobs, and pain points.",
        required: true,
        moduleId: "user_personas",
      }),
      section({
        id: "goals_and_non_goals",
        title: "Goals And Non-Goals",
        instructions: "Separate outcomes the feature should achieve from items explicitly out of scope.",
        required: true,
      }),
      section({
        id: "requirements",
        title: "Requirements",
        instructions: "List functional and non-functional requirements in clear, testable language.",
        required: true,
      }),
      section({
        id: "user_stories",
        title: "User Stories",
        instructions: "Convert requirements into user stories and acceptance notes.",
        required: true,
        moduleId: "user_personas",
      }),
      section({
        id: "success_metrics",
        title: "Success Metrics",
        instructions: "Define product, user, and business metrics for success.",
        required: true,
        moduleId: "metrics",
      }),
      section({
        id: "dependencies",
        title: "Dependencies",
        instructions: "Identify teams, APIs, systems, data, or decisions needed to ship.",
        required: false,
      }),
      section({
        id: "risks",
        title: "Risks",
        instructions: "Call out implementation, user, business, compliance, and adoption risks.",
        required: true,
        moduleId: "risk_analysis",
      }),
      section({
        id: "release_plan",
        title: "Release Plan",
        instructions: "Outline rollout, milestones, and launch sequencing.",
        required: false,
        moduleId: "implementation_plan",
      }),
      section({
        id: "validation_checklist",
        title: "Validation Checklist",
        instructions: "Define the checks the final PRD must pass before generation.",
        required: true,
        moduleId: "validation_checklist",
      }),
    ],
    validationCriteria: [
      "Requirements must be testable.",
      "Goals and non-goals must be explicit.",
      "Metrics must connect to user or business outcomes.",
      "Open questions must be separated from assumptions.",
    ],
  },
  {
    id: "debugging_bug_fix",
    name: "Debugging / Bug Fix Roadmap",
    artifacts: ["Code", "Technical Design"],
    roles: ["Developer"],
    taskCategories: ["engineering", "technical_design"],
    keywordSignals: ["bug", "error", "fix", "debug", "crash", "test", "api", "database", "regression"],
    defaultModules: ["assumptions", "root_cause_analysis", "test_cases", "validation_checklist", "risk_analysis"],
    optionalModules: ["api_examples", "database_schema", "implementation_plan", "sources_required"],
    defaultSourceMode: "none",
    defaultDepth: "L2",
    sections: [
      section({
        id: "symptom_summary",
        title: "Symptom Summary",
        instructions: "Summarize the bug, visible symptoms, frequency, and impact.",
        required: true,
      }),
      section({
        id: "reproduction_steps",
        title: "Reproduction Steps",
        instructions: "Capture known reproduction steps or list what is missing to reproduce.",
        required: true,
      }),
      section({
        id: "observed_vs_expected",
        title: "Observed Versus Expected",
        instructions: "Separate observed behavior from expected behavior.",
        required: true,
      }),
      section({
        id: "root_cause_hypotheses",
        title: "Root Cause Hypotheses",
        instructions: "List likely causes and the evidence needed to confirm or reject each one.",
        required: true,
        moduleId: "root_cause_analysis",
      }),
      section({
        id: "affected_surface_area",
        title: "Affected Surface Area",
        instructions: "Identify impacted components, APIs, data flows, users, and environments.",
        required: false,
      }),
      section({
        id: "fix_strategy",
        title: "Fix Strategy",
        instructions: "Describe the smallest safe fix and alternatives if the cause changes.",
        required: true,
        moduleId: "implementation_plan",
      }),
      section({
        id: "test_plan",
        title: "Test Plan",
        instructions: "Define regression tests, edge cases, and manual verification.",
        required: true,
        moduleId: "test_cases",
      }),
      section({
        id: "rollback_plan",
        title: "Rollback Plan",
        instructions: "Define rollback, monitoring, and recovery steps if the fix fails.",
        required: true,
        moduleId: "risk_analysis",
      }),
      section({
        id: "validation_checklist",
        title: "Validation Checklist",
        instructions: "Define the checks the final answer must pass before generation.",
        required: true,
        moduleId: "validation_checklist",
      }),
    ],
    validationCriteria: [
      "Final answer must include reproduction steps or missing reproduction context.",
      "Fix strategy must include tests.",
      "Risk and rollback must be included for production-facing bugs.",
      "Unknowns must not be presented as confirmed causes.",
    ],
  },
  {
    id: "backend_software",
    name: "Backend Software Roadmap",
    artifacts: ["Backend API", "Code", "Technical Design", "Implementation Plan"],
    roles: ["Developer", "Software Architect"],
    taskCategories: ["backend", "engineering", "technical_design"],
    keywordSignals: ["backend", "api", "endpoint", "server", "service", "microservice", "database", "auth", "queue", "cache"],
    defaultModules: ["assumptions", "implementation_plan", "api_examples", "database_schema", "test_cases", "validation_checklist"],
    optionalModules: ["risk_analysis", "metrics", "tradeoff_analysis", "sources_required"],
    defaultSourceMode: "none",
    defaultDepth: "L3",
    sections: [
      section({
        id: "backend_objective",
        title: "Backend Objective",
        instructions: "Define the service, user/business need, and backend capability to build.",
        required: true,
      }),
      section({
        id: "api_contracts",
        title: "API Contracts",
        instructions: "List endpoints, methods, request/response shapes, auth needs, and error semantics.",
        required: true,
        moduleId: "api_examples",
      }),
      section({
        id: "data_model",
        title: "Data Model",
        instructions: "Define entities, tables, relationships, migrations, constraints, and retention rules.",
        required: true,
        moduleId: "database_schema",
      }),
      section({
        id: "service_flow",
        title: "Service Flow",
        instructions: "Describe request flow, dependencies, queues, background jobs, caching, and failure paths.",
        required: true,
        moduleId: "implementation_plan",
      }),
      section({
        id: "backend_tests",
        title: "Backend Tests",
        instructions: "Define unit, integration, contract, security, and regression tests.",
        required: true,
        moduleId: "test_cases",
      }),
      section({
        id: "backend_risks",
        title: "Backend Risks",
        instructions: "Capture reliability, data integrity, security, scaling, and deployment risks.",
        required: false,
        moduleId: "risk_analysis",
      }),
      section({
        id: "validation_checklist",
        title: "Validation Checklist",
        instructions: "Define checks the final backend plan or answer must pass.",
        required: true,
        moduleId: "validation_checklist",
      }),
    ],
    validationCriteria: [
      "API contracts must be explicit.",
      "Data model and persistence risks must be addressed.",
      "Testing must cover integration and failure cases.",
      "Security and deployment risks must not be hidden.",
    ],
  },
  {
    id: "frontend_web",
    name: "Frontend Web Roadmap",
    artifacts: ["Frontend App", "Code", "Technical Design", "Implementation Plan"],
    roles: ["Developer", "Designer", "Product Manager"],
    taskCategories: ["frontend", "engineering", "technical_design"],
    keywordSignals: ["frontend", "web app", "react", "vue", "ui", "component", "responsive", "css", "browser", "accessibility"],
    defaultModules: ["assumptions", "implementation_plan", "validation_checklist", "test_cases", "risk_analysis"],
    optionalModules: ["user_personas", "metrics", "api_examples", "tradeoff_analysis", "sources_required"],
    defaultSourceMode: "none",
    defaultDepth: "L3",
    sections: [
      section({
        id: "frontend_goal",
        title: "Frontend Goal",
        instructions: "Define the user-facing experience, target users, and primary workflow.",
        required: true,
      }),
      section({
        id: "ui_structure",
        title: "UI Structure",
        instructions: "Plan pages, components, states, responsive behavior, empty states, and error states.",
        required: true,
        moduleId: "implementation_plan",
      }),
      section({
        id: "state_and_data",
        title: "State And Data Flow",
        instructions: "Define client state, API calls, loading behavior, caching, and mutation flow.",
        required: true,
        moduleId: "api_examples",
      }),
      section({
        id: "accessibility_and_quality",
        title: "Accessibility And Quality",
        instructions: "Plan keyboard behavior, focus states, semantic labels, contrast, and responsiveness.",
        required: true,
        moduleId: "validation_checklist",
      }),
      section({
        id: "frontend_tests",
        title: "Frontend Tests",
        instructions: "Define component, interaction, responsive, and end-to-end checks.",
        required: true,
        moduleId: "test_cases",
      }),
      section({
        id: "frontend_risks",
        title: "Frontend Risks",
        instructions: "Capture browser, performance, API, accessibility, and UX risks.",
        required: false,
        moduleId: "risk_analysis",
      }),
    ],
    validationCriteria: [
      "User workflow and UI states must be explicit.",
      "Data flow and API dependencies must be addressed.",
      "Accessibility and responsive behavior must be checked.",
      "Tests must cover interaction and failure states.",
    ],
  },
  {
    id: "architecture_review",
    name: "Architecture Review Roadmap",
    artifacts: ["Architecture Review", "Technical Design", "Strategy Memo"],
    roles: ["Software Architect", "Developer", "Executive"],
    taskCategories: ["technical_design", "engineering"],
    keywordSignals: ["architecture review", "review architecture", "system design", "scalability", "reliability", "distributed", "tradeoff"],
    defaultModules: ["assumptions", "risk_analysis", "validation_checklist", "implementation_plan"],
    optionalModules: ["api_examples", "database_schema", "metrics", "tradeoff_analysis", "sources_required"],
    defaultSourceMode: "none",
    defaultDepth: "L4",
    sections: [
      section({
        id: "architecture_scope",
        title: "Review Scope",
        instructions: "Define the system boundary, components, users, traffic, and decisions under review.",
        required: true,
      }),
      section({
        id: "current_architecture",
        title: "Current Architecture",
        instructions: "Summarize components, data flows, dependencies, storage, and integration points.",
        required: true,
      }),
      section({
        id: "quality_attributes",
        title: "Quality Attributes",
        instructions: "Evaluate scalability, reliability, security, maintainability, observability, and cost.",
        required: true,
        moduleId: "risk_analysis",
      }),
      section({
        id: "tradeoffs",
        title: "Tradeoffs And Alternatives",
        instructions: "Compare design options and call out operational tradeoffs.",
        required: true,
        moduleId: "implementation_plan",
      }),
      section({
        id: "architecture_recommendations",
        title: "Recommendations",
        instructions: "Prioritize changes by impact, effort, risk, and sequencing.",
        required: true,
      }),
      section({
        id: "validation_checklist",
        title: "Validation Checklist",
        instructions: "Define review checks and evidence needed before accepting recommendations.",
        required: true,
        moduleId: "validation_checklist",
      }),
    ],
    validationCriteria: [
      "Architecture boundaries and assumptions must be explicit.",
      "Risks and quality attributes must be evaluated.",
      "Recommendations must include tradeoffs and sequencing.",
      "Evidence gaps must be marked as missing context or source-needed.",
    ],
  },
  {
    id: "research_report",
    name: "Research Report Roadmap",
    artifacts: ["Research Report", "Competitive Analysis", "Strategy Memo"],
    roles: ["Researcher", "Founder", "Executive", "Business Analyst"],
    taskCategories: ["research", "analysis"],
    keywordSignals: ["research", "report", "sources", "citations", "literature", "market research", "evidence", "synthesize"],
    defaultModules: ["assumptions", "sources_required", "validation_checklist"],
    optionalModules: ["competitor_analysis", "market_landscape", "risk_analysis", "metrics"],
    defaultSourceMode: "source_needed_only",
    defaultDepth: "L3",
    sections: [
      section({
        id: "research_question",
        title: "Research Question",
        instructions: "Define the core question, audience, decision context, and scope boundaries.",
        required: true,
      }),
      section({
        id: "source_strategy",
        title: "Source Strategy",
        instructions: "Define source types, credibility rules, citation expectations, and source gaps.",
        required: true,
        moduleId: "sources_required",
      }),
      section({
        id: "findings_structure",
        title: "Findings Structure",
        instructions: "Plan themes, comparisons, evidence buckets, and synthesis logic.",
        required: true,
      }),
      section({
        id: "market_or_context",
        title: "Market Or Context",
        instructions: "Capture market, domain, category, or background context where relevant.",
        required: false,
        moduleId: "market_landscape",
      }),
      section({
        id: "recommendations",
        title: "Recommendations",
        instructions: "Define how findings should translate into conclusions or next actions.",
        required: true,
      }),
      section({
        id: "validation_checklist",
        title: "Validation Checklist",
        instructions: "Define checks for source quality, coverage, bias, and unsupported claims.",
        required: true,
        moduleId: "validation_checklist",
      }),
    ],
    validationCriteria: [
      "Research question and scope must be explicit.",
      "Claims needing evidence must be marked source-needed.",
      "Findings must distinguish evidence from assumptions.",
      "Recommendations must follow from the research structure.",
    ],
  },
  {
    id: "analytics_plan",
    name: "Analytics Roadmap",
    artifacts: ["Data Analysis", "Strategy Memo", "Research Report"],
    roles: ["Data Analyst", "Business Analyst", "Product Manager", "Executive"],
    taskCategories: ["data", "analysis"],
    keywordSignals: ["analytics", "data analysis", "dataset", "sql", "dashboard", "cohort", "funnel", "experiment", "chart"],
    defaultModules: ["assumptions", "metrics", "validation_checklist", "sources_required"],
    optionalModules: ["risk_analysis", "implementation_plan", "market_landscape", "tradeoff_analysis"],
    defaultSourceMode: "source_needed_only",
    defaultDepth: "L3",
    sections: [
      section({
        id: "analytics_question",
        title: "Analytics Question",
        instructions: "Define the business or product question and decision the analysis should support.",
        required: true,
      }),
      section({
        id: "data_requirements",
        title: "Data Requirements",
        instructions: "List datasets, fields, filters, date ranges, joins, and data quality assumptions.",
        required: true,
        moduleId: "sources_required",
      }),
      section({
        id: "metric_definitions",
        title: "Metric Definitions",
        instructions: "Define metrics, formulas, denominators, guardrails, and segmentation.",
        required: true,
        moduleId: "metrics",
      }),
      section({
        id: "analysis_method",
        title: "Analysis Method",
        instructions: "Plan SQL, cohorts, funnels, experiments, charts, or statistical checks.",
        required: true,
        moduleId: "implementation_plan",
      }),
      section({
        id: "insight_validation",
        title: "Insight Validation",
        instructions: "Define checks for bias, missing data, causality limits, and confidence.",
        required: true,
        moduleId: "validation_checklist",
      }),
    ],
    validationCriteria: [
      "Metrics must be defined clearly.",
      "Data requirements and assumptions must be explicit.",
      "Analysis method must match the question.",
      "Limitations and validation checks must be visible.",
    ],
  },
  {
    id: "complex_coding",
    name: "Complex Coding Roadmap",
    artifacts: ["Code", "Implementation Plan", "Technical Design"],
    roles: ["Developer", "Software Architect"],
    taskCategories: ["engineering", "technical_design"],
    keywordSignals: ["complex coding", "implement", "multi-file", "algorithm", "refactor", "integration", "library", "sdk", "build"],
    defaultModules: ["assumptions", "implementation_plan", "test_cases", "validation_checklist", "risk_analysis"],
    optionalModules: ["api_examples", "database_schema", "metrics", "tradeoff_analysis", "sources_required"],
    defaultSourceMode: "none",
    defaultDepth: "L3",
    sections: [
      section({
        id: "coding_goal",
        title: "Coding Goal",
        instructions: "Define the behavior to build, constraints, inputs, outputs, and affected surfaces.",
        required: true,
      }),
      section({
        id: "technical_approach",
        title: "Technical Approach",
        instructions: "Break the implementation into components, files, functions, data flow, and dependencies.",
        required: true,
        moduleId: "implementation_plan",
      }),
      section({
        id: "edge_cases",
        title: "Edge Cases",
        instructions: "List edge cases, failure modes, concurrency concerns, and compatibility risks.",
        required: true,
        moduleId: "risk_analysis",
      }),
      section({
        id: "testing_strategy",
        title: "Testing Strategy",
        instructions: "Define unit, integration, regression, and manual checks.",
        required: true,
        moduleId: "test_cases",
      }),
      section({
        id: "delivery_sequence",
        title: "Delivery Sequence",
        instructions: "Sequence implementation steps, verification, rollout, and cleanup.",
        required: true,
      }),
      section({
        id: "validation_checklist",
        title: "Validation Checklist",
        instructions: "Define checks the generated code answer must satisfy.",
        required: true,
        moduleId: "validation_checklist",
      }),
    ],
    validationCriteria: [
      "Implementation steps must be ordered and testable.",
      "Edge cases and risks must be covered.",
      "Tests must map to expected behavior.",
      "The answer must not skip required constraints.",
    ],
  },
  {
    id: "career_path",
    name: "Career Path Roadmap",
    artifacts: ["Career Roadmap", "Strategy Memo"],
    roles: ["Career Coach", "Developer", "Designer", "Data Analyst", "Product Manager"],
    taskCategories: ["career", "general"],
    keywordSignals: ["career", "career path", "learning path", "roadmap to become", "resume", "cv", "interview", "portfolio", "job search"],
    defaultModules: ["assumptions", "implementation_plan", "metrics", "validation_checklist"],
    optionalModules: ["risk_analysis", "sources_required"],
    defaultSourceMode: "none",
    defaultDepth: "L2",
    sections: [
      section({
        id: "career_goal",
        title: "Career Goal",
        instructions: "Define target role, timeline, current level, constraints, and motivation.",
        required: true,
      }),
      section({
        id: "skill_gap",
        title: "Skill Gap",
        instructions: "Identify required skills, current gaps, proof points, and priority order.",
        required: true,
        moduleId: "implementation_plan",
      }),
      section({
        id: "learning_plan",
        title: "Learning Plan",
        instructions: "Plan projects, study topics, practice loops, and portfolio artifacts.",
        required: true,
      }),
      section({
        id: "career_metrics",
        title: "Progress Metrics",
        instructions: "Define weekly or monthly indicators for learning, applications, interviews, and portfolio quality.",
        required: true,
        moduleId: "metrics",
      }),
      section({
        id: "risks_and_constraints",
        title: "Risks And Constraints",
        instructions: "Capture time, confidence, market, financial, and consistency risks with mitigations.",
        required: false,
        moduleId: "risk_analysis",
      }),
      section({
        id: "validation_checklist",
        title: "Validation Checklist",
        instructions: "Define checks for realism, sequencing, and measurable progress.",
        required: true,
        moduleId: "validation_checklist",
      }),
    ],
    validationCriteria: [
      "Career goal and current context must be explicit.",
      "Plan must include concrete projects or proof points.",
      "Progress metrics must be measurable.",
      "Risks and constraints must be realistic.",
    ],
  },
  {
    id: "generic_workflow",
    name: "Generic Work Roadmap",
    artifacts: ["General Roadmap", "Strategy Memo", "Research Report", "Technical Design", "Implementation Plan", "Unknown"],
    roles: [
      "Product Manager",
      "Researcher",
      "Developer",
      "Software Architect",
      "Data Analyst",
      "Founder",
      "Business Analyst",
      "Designer",
      "Marketer",
      "Executive",
      "Career Coach",
      "Unknown",
    ],
    taskCategories: ["general", "analysis", "business", "engineering", "research"],
    keywordSignals: ["plan", "roadmap", "outline", "structure", "framework", "guide"],
    defaultModules: ["assumptions", "validation_checklist", "implementation_plan"],
    optionalModules: ["risk_analysis", "sources_required", "metrics", "tradeoff_analysis"],
    defaultSourceMode: "none",
    defaultDepth: "L2",
    sections: [
      section({
        id: "intent_and_output",
        title: "Intent And Output",
        instructions: "Clarify what the user is trying to accomplish and what final artifact should be produced.",
        required: true,
      }),
      section({
        id: "assumptions_and_context",
        title: "Assumptions And Context",
        instructions: "List assumptions, known context, missing context, and boundaries.",
        required: true,
        moduleId: "assumptions",
      }),
      section({
        id: "work_steps",
        title: "Work Steps",
        instructions: "Break the work into ordered steps, decisions, dependencies, and handoffs.",
        required: true,
        moduleId: "implementation_plan",
      }),
      section({
        id: "quality_bar",
        title: "Quality Bar",
        instructions: "Define what would make the answer correct, complete, useful, and trustworthy for this task.",
        required: true,
        moduleId: "validation_checklist",
      }),
      section({
        id: "risks_and_unknowns",
        title: "Risks And Unknowns",
        instructions: "Call out uncertainty, likely failure modes, and where human judgment is needed.",
        required: false,
        moduleId: "risk_analysis",
      }),
    ],
    validationCriteria: [
      "Final answer must state assumptions and missing context.",
      "Work steps must be clear and actionable.",
      "Quality bar must be contextual, not a generic trust score.",
      "Uncertainty and human judgment points must remain visible.",
    ],
  },
];

export function getWorkflowTemplate(workflowId: WorkflowDefinition["id"]) {
  return workflowTemplates.find((template) => template.id === workflowId) ?? null;
}
